[package]
name = "leifstout/networker"
description = "A replacement for RemoteEvents"
version = "0.3.1"
license = "MIT"
authors = ["Leif Stout <leifstout@gmail.com>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml", "LICENSE"]

[dependencies]
Signal = "sleitnick/signal@2.0.3"